name: Run benchmarks

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  run-benchmarks:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install wrk -y

      - name: Install Setup
        run: "bash ./setup.sh"

      - name: Run benchmarks
        run: "./run_benchmarks.sh"
