name: Run benchmarks

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  run-benchmarks:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2

      - name: test
        run: "bash ./test.sh"

      - name: Push readme
        run: |
          git add README2.md
          git commit -m "update new readme2"
          git push

      # - name: Install Dependencies
      #   run: |
      #     sudo apt-get update && sudo apt-get install -y build-essential libssl-dev git curl wget wrk gnuplot
      #
      # - uses: actions/setup-go@v4
      #   with:
      #     go-version: "1.21.1"
      #
      # - uses:
      #     actions/setup-node@v4
      #
      # - uses: actions/setup-java@v3
      #   with:
      #     distribution: 'temurin'
      #     java-version: '17'
      #     cache: 'gradle'

          # Nginx configurations
          # RUN mkdir -p /var/cache/nginx-cache \
          #     /var/lib/nginx/body \
          #     /var/lib/nginx/proxy \
          #     /var/lib/nginx/fastcgi \
          #     /var/lib/nginx/uwsgi \
          #     /var/lib/nginx/scgi \
          #     /var/log/nginx \
          #     && touch /var/log/nginx/access.log /var/log/nginx/error.log \
          #     && chown -R www-data:www-data /var/cache/nginx-cache /var/log/nginx /var/lib/nginx

      # - name: Install Setup
      #   run: "bash ./setup.sh"

      # - name: Run benchmarks
      #   run: "./run_benchmarks.sh"
